### ISSUE TITLE
'pax_global_header' in tar file is not a directory

### ISSUE THREAD

**Issue by wdkrnls** [alezost/aurel#1]
I'm getting the following error when calling `aurel-info-download-package`:

```
aurel-download-unpack: The first entry 'pax_global_header' in tar file is not a directory
```

**Comment by alezost** [comment]
Ah, thanks for reporting!  Some tar-files have a special `pax_global_header` entry which is not a real file (you can see it if you open the tarball in emacs).  I've added support for this case, so it should be fixed now.  Please report if it is not.
