### ISSUE TITLE
Is aurel-filter-outdated outdated?

### ISSUE THREAD

**Issue by marcowahl** [alezost/aurel#2]
Hello!

Today aurel-package-search did not work for me.  I did the fix as below.

```
(defun aurel-filter-outdated (info)
  "Change `outdated' parameter of a package INFO.
Replace 1/0 with t/nil.
INFO is alist of parameter symbols and values.
Return modified info."
  (let ((param (assoc 'outdated info)))
    ;; (setcdr param (null (= 0 (cdr param))))
    (setcdr param (null (cdr param)))
    )
  info)
```

It looks ok for now but I actually did not really know what I was doing.  I hope you can do the right thing.

HTH and thank you very much for the software,  Marco

**Comment by alezost** [comment]
Ha-ha!  Yes, you are right, it is outdated.

"OutOfDate" parameter of [JSON info](https://wiki.archlinux.org/index.php/AurJson#info_2) was changed.
Previously it was just a boolean value (0/1), and now it may ether be
empty or a date when the package was flagged as outdated.  For example,
you can look at `M-x aurel-package-name akari` to see how it looks like
(it should work now).

Thank you very much for reporting and digging to
`aurel-filter-outdated`, it helped a lot!

**Comment by marcowahl** [comment]
Thank you!  In particular for the extra information.
