### ISSUE TITLE
AUR link to aurel package

### ISSUE THREAD

**Issue by igorepst** [alezost/aurel#3]
Hi,
The link, provided to AUR for the aurel package, is dead, as Arch reorganized all the AUR work (moved to git) some months ago. There is a backup however [here](http://pkgbuild.com/git/aur-mirror.git/tree/aurel).
In addition, the description about `pacman` is wrong, as it cannot be used to install from AUR (there are special [AUR helpers](https://wiki.archlinux.org/index.php/AUR_helpers) for that). Perhaps you meant manual installation (`makepkg` to build & `pacman` to install)?
Thank you

**Comment by alezost** [comment]
Yes, that's what I meant.  Eventually pacman is used anyway, even if you use helpers.

Since `aurel` is not in AUR anymore, I have removed the link.  Thank you for the info!
