### ISSUE TITLE
aurel-installed-packages invalid date

### ISSUE THREAD

**Issue by bricewge** [alezost/aurel#4]
Calling `aurel-installed-packages` return `byte-code: Invalid date: lun. 07 déc. 2015 17:16:00 CET`. Here is a trace of the error:

``` emacs-lisp
Debugger entered--Lisp error: (error "Invalid date: lun. 07 déc. 2015 17:16:00 CET")
  signal(error ("Invalid date: lun. 07 déc. 2015 17:16:00 CET"))
  error("Invalid date: %s" "lun. 07 déc. 2015 17:16:00 CET")
  byte-code("\300\301\302\217\207" [nil (byte-code "\301\302\303\304!!\"\207" [date apply encode-time parse-time-string timezone-make-date-arpa-standard] 5) ((error (error "Invalid date: %s" date)))] 3)
  date-to-time("lun. 07 déc. 2015 17:16:00 CET")
  aurel-filter-date(((installed-name . "ubuntu-keyring") (installed-version . "2012.05.19-2") (architecture . "any") (provides . "None") (depends . "gnupg") (depends-opt . "None") (required . "None") (optional-for . "debootstrap") (conflicts . "None") (replaces . "None") (installed-size . "17,00 KiB") (packager . "Unknown Packager") (build-date . "lun. 07 déc. 2015 17:16:00 CET") (install-date . "lun. 07 déc. 2015 17:16:14 CET") (reason . "Explicitly installed") (script . "No") (validated . "None")) date-to-time install-date build-date)
  aurel-pacman-filter-date(((installed-name . "ubuntu-keyring") (installed-version . "2012.05.19-2") (architecture . "any") (provides . "None") (depends . "gnupg") (depends-opt . "None") (required . "None") (optional-for . "debootstrap") (conflicts . "None") (replaces . "None") (installed-size . "17,00 KiB") (packager . "Unknown Packager") (build-date . "lun. 07 déc. 2015 17:16:00 CET") (install-date . "lun. 07 déc. 2015 17:16:14 CET") (reason . "Explicitly installed") (script . "No") (validated . "None")))
  aurel-apply-filters((("Name" . "ubuntu-keyring") ("Version" . "2012.05.19-2") ("Description" . "GnuPG keys of the Ubuntu archive") ("Architecture" . "any") ("URL" . "http://packages.ubuntu.com/trusty/ubuntu-keyring") ("Licenses" . "GPL") ("Groups" . "None") ("Provides" . "None") ("Depends On" . "gnupg") ("Optional Deps" . "None") ("Required By" . "None") ("Optional For" . "debootstrap") ("Conflicts With" . "None") ("Replaces" . "None") ("Installed Size" . "17,00 KiB") ("Packager" . "Unknown Packager") ("Build Date" . "lun. 07 déc. 2015 17:16:00 CET") ("Install Date" . "lun. 07 déc. 2015 17:16:14 CET") ("Install Reason" . "Explicitly installed") ("Install Script" . "No") ("Validated By" . "None")) (aurel-pacman-filter-intern aurel-pacman-filter-date))
  #[257 "\302\300\"\211\205
```

**Comment by alezost** [comment]
Ah, it's because of localization.  As you can check in emacs:

```
M-: (date-to-time "Wed Dec 16 16:42:17 2015")
```

gives some value, while:

```
M-: (date-to-time "lun. 07 déc. 2015 17:16:14 CET")
```

gives an error.  If I understand correctly, you have a French locale, so
when you run pacman, you have some french output (including the time).

I'm currently not on "Arch Linux", and I could check it only in
several days, but I'm sure that replacing "LANG=" with "LC_ALL="
in https://github.com/alezost/aurel/blob/master/aurel.el#L530
will fix this issue.

So if you don't mind, could you check that the following command gives
a standard date output (not frenchized one):

```
LC_ALL=en_US.utf8 pacman -Qi emacs
```

Thanks for reporting!

P.S.  Instead of `en_US.utf8` we can probably just use `C`, I'm not sure
if it will have any downsides though.

**Comment by bricewge** [comment]
So replacing `"LANG="` by `"LC_ALL="` or `"LC_ALL=C"` doesn't work, it respectively produce:
- `Wed 13 May 2015 06:23:44 PM CEST`
- `Wed May 13 18:23:44 2015`

I think using `C` will be better than `en_US.utf8` because some may not have this locale on their system.

**Comment by alezost** [comment]
Hm, why do you say "doesn't work"?  Both time strings are parsed
correctly with `date-to-time`.

**Comment by bricewge** [comment]
My bad. I missed part of the error messages: `byte-code: Invalid date: Wed May 13 18:23:44 2015`.
It doesn't work because I don't get the list of the packages installed in my system.

**Comment by alezost** [comment]
Sorry, I don't understand.  What have you changed, and how did
you get this error?

**Comment by alezost** [comment]
I have just checked, and it looks like using LC_ALL fixes the
issue.  So I have pushed this change, and switched the default
locale to "C".  Please report if you still have this issue,
thanks!

**Comment by bricewge** [comment]
I just checked with your two changes and I still get `byte-code: Invalid date: Wed May 13 18:23:44 2015`.

**Comment by alezost** [comment]
'byte-code' tells this comes from a compiled elisp code.  Did you check
aurel from this git repo and did you compile it?  Perhaps it's a stale
byte-code from the previous version.

Also could you post the full backtrace?

**Comment by bricewge** [comment]
I just have reinstalled `aurel` from the git repo but the same error appear: `byte-code: Invalid date: Wed May 13 18:23:44 2015`.

Here is the backtrace:

```
Debugger entered--Lisp error: (error "Invalid date: Wed May 13 18:23:44 2015")
  signal(error ("Invalid date: Wed May 13 18:23:44 2015"))
  error("Invalid date: %s" "Wed May 13 18:23:44 2015")
  byte-code("\300\301\302\217\207" [nil (byte-code "\301\302\303\304!!\"\207" [date apply encode-time parse-time-string timezone-make-date-arpa-standard] 5) ((error (error "Invalid date: %s" date)))] 3)
  date-to-time("Wed May 13 18:23:44 2015")
  aurel-filter-date(((installed-name . "pdfmasher") (installed-version . "0.7.4-2") (architecture . "any") (provides . "None") (depends . "python  python-pyqt4  python-cssutils  python-lxml  python-markdown  python-cssselect") (depends-opt . "None") (required . "None") (optional-for . "None") (conflicts . "None") (replaces . "None") (installed-size . "9.62 MiB") (packager . "Unknown Packager") (build-date . "Wed May 13 18:23:44 2015") (install-date . "Wed May 13 18:23:49 2015") (reason . "Explicitly installed") (script . "No") (validated . "None")) date-to-time install-date build-date)
  aurel-pacman-filter-date(((installed-name . "pdfmasher") (installed-version . "0.7.4-2") (architecture . "any") (provides . "None") (depends . "python  python-pyqt4  python-cssutils  python-lxml  python-markdown  python-cssselect") (depends-opt . "None") (required . "None") (optional-for . "None") (conflicts . "None") (replaces . "None") (installed-size . "9.62 MiB") (packager . "Unknown Packager") (build-date . "Wed May 13 18:23:44 2015") (install-date . "Wed May 13 18:23:49 2015") (reason . "Explicitly installed") (script . "No") (validated . "None")))
  aurel-apply-filters((("Name" . "pdfmasher") ("Version" . "0.7.4-2") ("Description" . "PDF to eBook Conversion Tool") ("Architecture" . "any") ("URL" . "http://www.hardcoded.net/pdfmasher/") ("Licenses" . "GPL") ("Groups" . "None") ("Provides" . "None") ("Depends On" . "python  python-pyqt4  python-cssutils  python-lxml  python-markdown  python-cssselect") ("Optional Deps" . "None") ("Required By" . "None") ("Optional For" . "None") ("Conflicts With" . "None") ("Replaces" . "None") ("Installed Size" . "9.62 MiB") ("Packager" . "Unknown Packager") ("Build Date" . "Wed May 13 18:23:44 2015") ("Install Date" . "Wed May 13 18:23:49 2015") ("Install Reason" . "Explicitly installed") ("Install Script" . "No") ("Validated By" . "None")) (aurel-pacman-filter-intern aurel-pacman-filter-date))
  #[257 "\302\300\"\211\205
```

**Comment by alezost** [comment]
OMG!  It looks like (date-to-time "Wed May 13 18:23:44 2015") errors for
you.  Could you evaluate it?  For me it returns (21843 27776).

**Comment by bricewge** [comment]
With my emacs config I get the result as usual: `byte-code: Invalid date: Wed May 13 18:23:44 2015`.
And without any configuration loaded I have the same result as you...

**Comment by alezost** [comment]
Wow, cool.  Maybe some emacs package does something with
`date-to-time` (advise it, for example), dunno :-)

What about: (parse-time-string "Wed May 13 18:23:44 2015")?
Does it also give an error?

BTW is your config public?

**Comment by bricewge** [comment]
Sorry to have bothered you with this issue. `parse-time-string` work fine. Yes my config is mainly in this file: https://github.com/bricewge/dotfiles/blob/master/emacs/bricewge.org
This looks like a very strange issue to me.

**Comment by alezost** [comment]
Hm, maybe (setq system-time-locale "fr_FR.UTF-8") has this strange
effect.  However I've tried it, but

```
(date-to-time "Wed May 13 18:23:44 2015")
```

still parses successfully.

I really wonder what changes this time parsing for you.  This is
exciting!

**Comment by alezost** [comment]
Yes, I found it!  You changed `parse-time-weekdays` and `parse-time-months`, so default ISO time values are not parsed properly anymore

**Comment by alezost** [comment]
I don't think these variables are intended to be customized by a user.  It looks like their purpose is to serve as auxiliary variables in time parsing machinery.  So I bet if you comment setting these `parse-time-...` variables, you'll not get an error in `date-to-time` anymore.

**Comment by alezost** [comment]
However, If you need to have these French values in
`parse-time-weekdays` and `parse-time-months`, I think you can
just add them instead of replacing the original values, so something
like this will do:

``` elisp
(use-package parse-time
  :config
  (setq parse-time-weekdays
        (append parse-time-weekdays
                '(("dim" . 0)
                  ("lun" . 1)
                  ("mar" . 2)
                  ("mer" . 3)
                  ("jeu" . 4)
                  ("ven" . 5)
                  ("sam" . 6)
                  ("dimanche" . 0)
                  ("lundi" . 1)
                  ("mardi" . 2)
                  ("mercredi" . 3)
                  ("jeudi" . 4)
                  ("vendredi" . 5)
                  ("samedi" . 6)))))
```

But I talk too much, shutting down :-)

Please let me know, if this issue still persists after all.

**Comment by bricewge** [comment]
Thanks a lot!! I think it would have taken me some time to figure out it was coming from this part.
This was exactly the source of the issue. I had put this in my config some years ago when the org-mode manual was advising to do so, fortunately they fixed it.

**Comment by alezost** [comment]
Great!  I'm glad all the misteries are solved :-)
Thanks again for reporting about the problem.
