### ISSUE TITLE
hl-line-mode in info-list

### ISSUE THREAD

**Issue by rogorido** [alezost/aurel#8]
Hi,

first of all, thanks for this wonderful package!

Second: what is the best method to activate hl-line-mode in the list buffer?

**Comment by alezost** [comment]
Hello and thanks!

As for me, I just enable `hl-line-mode` in all modes derived from `tabulated-list-mode`, like this:

```elisp
(add-hook 'tabulated-list-mode-hook 'hl-line-mode)
```

**Comment by rogorido** [comment]
exactly! I know that it should be very simple...

Thanks again for the wonderful package! (BTW: your very clear code in lisp is very good for beginners to learn a little bit lisp!)

**Comment by alezost** [comment]
Thank you :-)
